### ISSUE TITLE
Add compatibility with older xp bottles

### ISSUE THREAD

**Issue by AndrewCheedle** [Fruitloopins/XPManager#1]
The current compatibility with the older plugin is only about converting older bottles to newer ones, not adressing the issue of older bottles in chest shops being defunct and requiring to be manually removed.

Solution 

Either automatically remove older bottle xp shops so they dont need manual removing which would be tiresome for players or add a command that would make it possible to get older xp bottles as well in order to continue the 2 bottle plugins along each other

**Comment by Fruitloopins** [comment]
no

**Comment by AndrewCheedle** [comment]
your evil
